# Generated by Django 3.1.7 on 2021-04-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210423_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(default='slug here', max_length=50, unique=True),
        ),
    ]
