# Generated by Django 3.1.7 on 2021-04-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210423_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='show_on_lists',
            field=models.BooleanField(default=False, help_text="Choose whether this article should be visible on lists or only accesible trough direct urls. Useful basic articles like:'rules' or 'contact'"),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(default='Text here', help_text='HTML tags are allowed', max_length=15000),
        ),
    ]
