# Generated by Django 3.1.7 on 2021-04-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20210426_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='slug-here', help_text='This will appear in a URL, it should resemble the title', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='Title here', max_length=110),
        ),
    ]
