# Generated by Django 3.1.7 on 2021-05-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20210427_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='article',
            name='show_on_lists',
            field=models.BooleanField(default=False, help_text="Choose whether this article should be visible on lists or only accesible trough direct urls.         Leave disabled for hardcoded articles like:'rules' or 'contact'"),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='slug-here', help_text='Slug will appear in a URL, it be short and resemble the title', max_length=60, unique=True),
        ),
    ]
